// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using CleanArchReference.Infrastructure.Data.Context;

#nullable disable

namespace CleanArchReference.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.EmpresaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Regime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("EmpresaId", "Competencia");

                    b.ToTable("Obrigacoes", (string)null);
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoTagEntity", b =>
                {
                    b.Property<Guid>("ObrigacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ObrigacaoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ObrigacaoTags", (string)null);
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoEntity", b =>
                {
                    b.HasOne("CleanArchReference.Infrastructure.Data.Entities.EmpresaEntity", "Empresa")
                        .WithMany("Obrigacoes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoTagEntity", b =>
                {
                    b.HasOne("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoEntity", "Obrigacao")
                        .WithMany("Tags")
                        .HasForeignKey("ObrigacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchReference.Infrastructure.Data.Entities.TagEntity", "Tag")
                        .WithMany("Obrigacoes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obrigacao");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.EmpresaEntity", b =>
                {
                    b.Navigation("Obrigacoes");
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.ObrigacaoEntity", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("CleanArchReference.Infrastructure.Data.Entities.TagEntity", b =>
                {
                    b.Navigation("Obrigacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
